[package]
name = "native-cighash-all-mock-tx-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-hash = "0.119.0"
cighash-all-utils = { path = "../cighash-all-utils", features = ["std"] }
