name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "true"
    - name: Install llvm
      run: sudo apt update && sudo apt install -y clang llvm clang-format lld
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install riscv64 target
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Build, test, clippy, format
      run: make build test clippy fmt
    - name: git diff
      run: git diff --exit-code
